AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  helloworld:
    Properties:
      CodeUri: s3://serverless-trial-d895230cb5d94bb2c12b9ff415/2756d5ac8eb0d9ab7eeb07326944587c
      Description: ''
      Events:
        Get:
          Properties:
            Method: GET
            Path: /hello
          Type: Api
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: arn:aws:iam::940573688703:role/service-role/lambda-hello-world-role
      Runtime: python3.6
      Timeout: 1
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
